require("modules.autocomplete")
require("modules.bufferline")
require("modules.colorschemes")
require("modules.dashboard")
require("modules.lualine")
require("modules.mason")
require("modules.nvimtree")
require("modules.whichkey")
require("modules.telescope")
require("modules.comment")
require("modules.impatient")
require("modules.gitsigns")
require("modules.treesitter")
require("modules.trouble")
require("modules.devicons")
require("modules.toggleterm")

